import fs from 'node:fs/promises';
import path from 'node:path';

import {
  OrganisationSchema as PackageOrganisationSchema,
  RoleDefinitionSchema as PackageRoleDefinitionSchema,
  SeedVerbSchema as PackageSeedVerbSchema,
  SeedError as PackageSeedError,
  SeedInputSchema,
  seedRole as packageSeedRole,
} from '@praxis/seed';
import { simpleGit, type StatusResult } from 'simple-git';
import { z } from 'zod';

import { detectMode } from './role-home.ts';

/**
 * Re-exported schemas so the dashboard's existing call sites (the wizard
 * API route and the research route) keep their current import paths. The
 * shapes are now owned by `@praxis/seed`; this file only adds dashboard-
 * specific behaviour (the two-commit dance and the framework-repo tidy).
 */
export const SeedVerbSchema = PackageSeedVerbSchema;
export const OrganisationSchema = PackageOrganisationSchema;
export const RoleDefinitionSchema = PackageRoleDefinitionSchema;
export const SeedRequestSchema = SeedInputSchema;

export type SeedRequest = z.infer<typeof SeedInputSchema>;
export type Organisation = z.infer<typeof PackageOrganisationSchema>;
export type RoleDefinition = z.infer<typeof PackageRoleDefinitionSchema>;

export interface SeedResult {
  ok: true;
  role_home: string;
  redirect: string;
  commits: string[];
}

/**
 * Dashboard-flavour error: carries an HTTP status so the API route can map
 * it to a response code without a separate translation layer. Wraps the
 * package's `SeedError` for the parts of the flow it handles.
 */
export class SeedError extends Error {
  constructor(
    message: string,
    public readonly status: number = 400,
  ) {
    super(message);
    this.name = 'SeedError';
  }
}

interface SeedEnv {
  roleHome: string;
  templateRoot: string;
}

/**
 * The wizard's submit handler. Two visible commits:
 *   1. feat: seed role from praxis-framework template
 *   2. chore: tidy framework-only files post-seed
 *
 * Refuses if the role is already populated or the working tree is dirty.
 * The actual file writing is delegated to `@praxis/seed`; the dashboard
 * keeps the git/repo concerns here because they're specific to seeding
 * the framework checkout itself, not seeding into an arbitrary directory.
 */
export async function seedRole(req: SeedRequest, env: SeedEnv): Promise<SeedResult> {
  const { roleHome, templateRoot } = env;

  if (detectMode(roleHome) !== 'seed') {
    throw new SeedError('Role is already seeded — persona.md exists at the role home.', 409);
  }
  if (!(await pathExists(templateRoot))) {
    throw new SeedError(`Template directory missing: ${templateRoot}`, 500);
  }

  const git = simpleGit(roleHome);
  if (!(await git.checkIsRepo())) {
    throw new SeedError(
      'Role home is not a git repository. Initialise one (git init) before running the wizard.',
      400,
    );
  }
  const status = await git.status();
  if (!isCleanIgnoringPraxis(status)) {
    throw new SeedError(
      'Working tree has uncommitted changes. Commit or stash them before running the wizard.',
      409,
    );
  }

  // ---- Commit 1: seed --------------------------------------------------
  // Delegate the file IO to @praxis/seed. Pass overwrite: true because the
  // framework checkout has the template/ dir at the role root and the
  // existing .gitignore is already there — this is the original behaviour
  // (the dashboard always wrote without a conflict check) and the `tidy`
  // step below cleans up the framework-only artefacts post-seed.
  const result = await packageSeedRole(req, roleHome, {
    templatePath: templateRoot,
    overwrite: true,
  }).catch((err: unknown) => {
    // Translate package errors to dashboard errors so the API route's
    // status mapping continues to work unchanged.
    if (err instanceof PackageSeedError) {
      const status = err.code === 'TARGET_CONFLICT' ? 409 : err.code === 'INVALID_INPUT' ? 422 : 500;
      throw new SeedError(err.message, status);
    }
    throw err;
  });
  await git.add(result.filesWritten);
  await git.commit([
    'feat: seed role from praxis-framework template',
    `Generated by praxis dashboard wizard for ${req.role_definition.role_name}.`,
  ]);

  // ---- Commit 2: tidy --------------------------------------------------
  const tidiedPaths = await tidyFrameworkFiles(env);
  for (const p of tidiedPaths) {
    await git.add(p);
  }
  await git.commit([
    'chore: tidy framework-only files post-seed',
    'Removed template/, examples/, scripts/new-role.sh, and .praxis/ now that the role is populated.',
  ]);

  return {
    ok: true,
    role_home: roleHome,
    redirect: '/',
    commits: ['feat: seed role from praxis-framework template', 'chore: tidy framework-only files post-seed'],
  };
}

async function tidyFrameworkFiles(env: SeedEnv): Promise<string[]> {
  const tidied: string[] = [];

  const templateDir = path.join(env.roleHome, 'template');
  if (await pathExists(templateDir)) {
    await fs.rm(templateDir, { recursive: true, force: true });
    tidied.push('template');
  }
  const examplesDir = path.join(env.roleHome, 'examples');
  if (await pathExists(examplesDir)) {
    await fs.rm(examplesDir, { recursive: true, force: true });
    tidied.push('examples');
  }
  const newRoleScript = path.join(env.roleHome, 'scripts', 'new-role.sh');
  if (await pathExists(newRoleScript)) {
    await fs.rm(newRoleScript, { force: true });
    tidied.push(path.join('scripts', 'new-role.sh'));
  }
  // Research artefacts — only present if the operator went down the
  // research-and-design path. Always safe to remove post-seed. The template's
  // .gitignore already includes `.praxis/`, so the directory is untracked and
  // we don't stage the deletion (git would error on a path it never tracked).
  const praxisDir = path.join(env.roleHome, '.praxis');
  if (await pathExists(praxisDir)) {
    await fs.rm(praxisDir, { recursive: true, force: true });
  }
  // Replace README.md with a role-shaped one (from the wizard's persona, looked up via persona.md).
  const personaPath = path.join(env.roleHome, 'persona.md');
  let roleName = 'this role';
  let description = '';
  try {
    const personaText = await fs.readFile(personaPath, 'utf-8');
    const titleMatch = /^# Persona — (.+)$/m.exec(personaText);
    if (titleMatch && titleMatch[1]) roleName = titleMatch[1].trim();
  } catch {
    /* ignore */
  }
  const claudePath = path.join(env.roleHome, 'CLAUDE.md');
  try {
    const claudeText = await fs.readFile(claudePath, 'utf-8');
    const lines = claudeText.split('\n');
    // The first non-heading, non-empty line after the H1 is the description.
    for (let i = 1; i < lines.length; i++) {
      const line = (lines[i] ?? '').trim();
      if (line.length === 0) continue;
      if (line.startsWith('#')) continue;
      description = line;
      break;
    }
  } catch {
    /* ignore */
  }
  const readme = renderReadme(roleName, description);
  await fs.writeFile(path.join(env.roleHome, 'README.md'), readme, 'utf-8');
  tidied.push('README.md');

  return tidied;
}

function renderReadme(roleName: string, description: string): string {
  const desc = description.length > 0 ? description : '';
  return [
    `# ${roleName}`,
    '',
    desc,
    '',
    'Built with [praxis-framework](https://github.com/steveworley/praxis-framework).',
    '',
    '## Running',
    '',
    '```bash',
    '# Start the supervisor dashboard',
    'cd dashboard && npm install && npm run start',
    '# Open http://localhost:4321/',
    '',
    '# Open Claude Code in the role to drive it',
    'claude',
    '```',
    '',
  ].join('\n');
}

/**
 * Treat the working tree as clean if the only "dirty" entries are research
 * artefacts inside `.praxis/` — those are temporary handoff files written by
 * the research engine and will be cleaned up in commit 2 of the seed flow.
 */
function isCleanIgnoringPraxis(status: StatusResult): boolean {
  if (status.isClean()) return true;
  const everything = [
    ...status.not_added,
    ...status.created,
    ...status.modified,
    ...status.deleted,
    ...status.conflicted,
    ...status.staged,
  ];
  if (everything.length === 0) return false;
  return everything.every((p) => p === '.praxis' || p.startsWith('.praxis/'));
}

async function pathExists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}
