import fs from 'node:fs/promises';
import path from 'node:path';

import { simpleGit, type StatusResult } from 'simple-git';
import { z } from 'zod';

import { detectMode } from './role-home.ts';

export const SeedAgentSchema = z.object({
  slug: z
    .string()
    .min(1)
    .max(60)
    .regex(/^[a-z][a-z0-9-]*$/, 'slug must be lowercase kebab-case'),
  purpose: z.string().min(1).max(200),
});

export const OrganisationSchema = z.object({
  name: z.string().min(1).max(160),
  website: z.string().max(240).optional(),
  sector: z.string().max(160).optional(),
  size: z.enum(['solo', 'small', 'mid', 'large', 'enterprise']).optional(),
  description: z.string().max(1200).optional(),
  moats: z.string().max(1200).optional(),
  customer_profile: z.string().max(1200).optional(),
});

export const RoleDefinitionSchema = z.object({
  role_name: z.string().min(1).max(120),
  working_title: z.string().max(120).optional(),
  one_sentence_purpose: z.string().min(1).max(280),
  day_to_day: z.string().max(1200).optional(),
});

export const SeedRequestSchema = z.object({
  organisation: OrganisationSchema,
  role_definition: RoleDefinitionSchema,
  identity: z
    .object({
      email: z.string().max(120).optional(),
      location: z.string().max(120).optional(),
      reports_to: z.string().max(120).optional(),
    })
    .default({}),
  voice_traits: z
    .array(
      z.object({
        label: z.string().min(1).max(80),
        detail: z.string().min(1).max(280),
      }),
    )
    .min(1)
    .max(8),
  capabilities: z.array(z.string().min(1).max(280)).max(10).default([]),
  inhibitions: z.array(z.string().min(1).max(280)).max(10).default([]),
  initial_agents: z.array(SeedAgentSchema).max(5).default([]),
});

export type SeedRequest = z.infer<typeof SeedRequestSchema>;
export type Organisation = z.infer<typeof OrganisationSchema>;
export type RoleDefinition = z.infer<typeof RoleDefinitionSchema>;

export interface SeedResult {
  ok: true;
  role_home: string;
  redirect: string;
  commits: string[];
}

export class SeedError extends Error {
  constructor(
    message: string,
    public readonly status: number = 400,
  ) {
    super(message);
    this.name = 'SeedError';
  }
}

interface SeedEnv {
  roleHome: string;
  templateRoot: string;
}

/**
 * The wizard's submit handler. Two visible commits:
 *   1. feat: seed role from praxis-framework template
 *   2. chore: tidy framework-only files post-seed
 *
 * Refuses if the role is already populated or the working tree is dirty.
 */
export async function seedRole(req: SeedRequest, env: SeedEnv): Promise<SeedResult> {
  const { roleHome, templateRoot } = env;

  if (detectMode(roleHome) !== 'seed') {
    throw new SeedError('Role is already seeded — agents/persona.md exists at the role home.', 409);
  }
  if (!(await pathExists(templateRoot))) {
    throw new SeedError(`Template directory missing: ${templateRoot}`, 500);
  }

  const git = simpleGit(roleHome);
  if (!(await git.checkIsRepo())) {
    throw new SeedError(
      'Role home is not a git repository. Initialise one (git init) before running the wizard.',
      400,
    );
  }
  const status = await git.status();
  if (!isCleanIgnoringPraxis(status)) {
    throw new SeedError(
      'Working tree has uncommitted changes. Commit or stash them before running the wizard.',
      409,
    );
  }

  // ---- Commit 1: seed --------------------------------------------------
  const writtenPaths = await writeSeedFiles(req, env);
  await git.add(writtenPaths);
  await git.commit([
    'feat: seed role from praxis-framework template',
    `Generated by praxis dashboard wizard for ${req.role_definition.role_name}.`,
  ]);

  // ---- Commit 2: tidy --------------------------------------------------
  const tidiedPaths = await tidyFrameworkFiles(env);
  // Stage deletions plus rewritten README.
  for (const p of tidiedPaths) {
    await git.add(p);
  }
  await git.commit([
    'chore: tidy framework-only files post-seed',
    'Removed template/, examples/, scripts/new-role.sh, and .praxis/ now that the role is populated.',
  ]);

  return {
    ok: true,
    role_home: roleHome,
    redirect: '/',
    commits: ['feat: seed role from praxis-framework template', 'chore: tidy framework-only files post-seed'],
  };
}

interface RolePathPair {
  source: string; // template-relative
  target: string; // role-home-relative
}

const TEMPLATE_FILES: RolePathPair[] = [
  { source: 'CLAUDE.md', target: 'CLAUDE.md' },
  { source: 'agents/persona.md', target: 'agents/persona.md' },
  { source: 'agents/escalate.md', target: 'agents/escalate.md' },
  { source: 'agents/proposed/README.md', target: 'agents/proposed/README.md' },
  { source: 'memory/README.md', target: 'memory/README.md' },
  { source: 'escalations/README.md', target: 'escalations/README.md' },
  { source: '.gitignore', target: '.gitignore' },
  { source: 'bin/log', target: 'bin/log' },
];

const SEED_DIRS: string[] = [
  'agents',
  'agents/proposed',
  'bin',
  'lib',
  'memory',
  'memory/people',
  'memory/accounts',
  'memory/notes',
  'escalations',
];

const GITKEEP_LEAVES: string[] = [
  'agents/proposed',
  'lib',
  'memory/people',
  'memory/accounts',
  'memory/notes',
  'escalations',
];

async function writeSeedFiles(req: SeedRequest, env: SeedEnv): Promise<string[]> {
  const written: string[] = [];

  for (const dir of SEED_DIRS) {
    await fs.mkdir(path.join(env.roleHome, dir), { recursive: true });
  }

  const roleName = req.role_definition.role_name;

  for (const pair of TEMPLATE_FILES) {
    const src = path.join(env.templateRoot, pair.source);
    let body = await fs.readFile(src, 'utf-8');
    // bin/log is a verbatim Python script — no template substitution, no
    // role-shaped injection. Every role gets the same logger.
    if (pair.target !== 'bin/log') {
      body = body.replace(/\{ROLE_NAME\}/g, roleName);
      if (pair.target === 'CLAUDE.md') {
        body = injectClaudeDescription(body, req.role_definition.one_sentence_purpose);
      }
      if (pair.target === 'agents/persona.md') {
        body = injectPersona(body, req);
      }
    }
    const dst = path.join(env.roleHome, pair.target);
    await fs.mkdir(path.dirname(dst), { recursive: true });
    await fs.writeFile(dst, body, 'utf-8');
    if (pair.target === 'bin/log') {
      // Restore the executable bit — fs.writeFile drops it.
      await fs.chmod(dst, 0o755);
    }
    written.push(pair.target);
  }

  // Stub agents.
  for (const agent of req.initial_agents) {
    const target = path.join('agents', `${agent.slug}.md`);
    const dst = path.join(env.roleHome, target);
    if (await pathExists(dst)) continue;
    const body = renderAgentStub(req, agent);
    await fs.writeFile(dst, body, 'utf-8');
    written.push(target);
  }

  // .gitkeep on empty leaves.
  for (const leaf of GITKEEP_LEAVES) {
    const dirPath = path.join(env.roleHome, leaf);
    const entries = await fs.readdir(dirPath);
    if (entries.length === 0) {
      const keep = path.join(leaf, '.gitkeep');
      await fs.writeFile(path.join(env.roleHome, keep), '', 'utf-8');
      written.push(keep);
    }
  }

  return written;
}

async function tidyFrameworkFiles(env: SeedEnv): Promise<string[]> {
  const tidied: string[] = [];

  const templateDir = path.join(env.roleHome, 'template');
  if (await pathExists(templateDir)) {
    await fs.rm(templateDir, { recursive: true, force: true });
    tidied.push('template');
  }
  const examplesDir = path.join(env.roleHome, 'examples');
  if (await pathExists(examplesDir)) {
    await fs.rm(examplesDir, { recursive: true, force: true });
    tidied.push('examples');
  }
  const newRoleScript = path.join(env.roleHome, 'scripts', 'new-role.sh');
  if (await pathExists(newRoleScript)) {
    await fs.rm(newRoleScript, { force: true });
    tidied.push(path.join('scripts', 'new-role.sh'));
  }
  // Research artefacts — only present if the operator went down the
  // research-and-design path. Always safe to remove post-seed. The template's
  // .gitignore already includes `.praxis/`, so the directory is untracked and
  // we don't stage the deletion (git would error on a path it never tracked).
  const praxisDir = path.join(env.roleHome, '.praxis');
  if (await pathExists(praxisDir)) {
    await fs.rm(praxisDir, { recursive: true, force: true });
  }
  // Replace README.md with a role-shaped one (from the wizard's persona, looked up via persona.md).
  const personaPath = path.join(env.roleHome, 'agents', 'persona.md');
  let roleName = 'this role';
  let description = '';
  try {
    const personaText = await fs.readFile(personaPath, 'utf-8');
    const titleMatch = /^# Persona — (.+)$/m.exec(personaText);
    if (titleMatch && titleMatch[1]) roleName = titleMatch[1].trim();
  } catch {
    /* ignore */
  }
  const claudePath = path.join(env.roleHome, 'CLAUDE.md');
  try {
    const claudeText = await fs.readFile(claudePath, 'utf-8');
    const lines = claudeText.split('\n');
    // The first non-heading, non-empty line after the H1 is the description.
    for (let i = 1; i < lines.length; i++) {
      const line = (lines[i] ?? '').trim();
      if (line.length === 0) continue;
      if (line.startsWith('#')) continue;
      description = line;
      break;
    }
  } catch {
    /* ignore */
  }
  const readme = renderReadme(roleName, description);
  await fs.writeFile(path.join(env.roleHome, 'README.md'), readme, 'utf-8');
  tidied.push('README.md');

  return tidied;
}

function injectClaudeDescription(body: string, description: string): string {
  // Replace the placeholder line `{One-line first-person description...}`
  return body.replace(/\{One-line first-person description[^}]*\}/, description);
}

export function injectPersona(body: string, req: SeedRequest): string {
  let out = body;

  // Organisation — context block injected at the top.
  out = replaceSection(out, 'Organisation', renderOrganisationSection(req.organisation));

  // Identity bullets — drop placeholder, write operator-supplied identity.
  const identityBullets: string[] = [
    `- **Full name**: ${req.role_definition.role_name}`,
    `- **Role**: ${req.role_definition.one_sentence_purpose}`,
  ];
  if (req.identity.location) identityBullets.push(`- **Location**: ${req.identity.location}`);
  if (req.identity.reports_to) identityBullets.push(`- **Reports to**: ${req.identity.reports_to}`);
  if (req.identity.email) identityBullets.push(`- **Email**: ${req.identity.email}`);

  out = replaceSection(out, 'Identity', identityBullets.join('\n'));

  // Voice & Personality.
  const voiceBullets = req.voice_traits
    .map((t) => `- **${t.label}** -- ${t.detail}`)
    .join('\n');
  out = replaceSection(out, 'Voice & Personality', voiceBullets);

  // Capabilities.
  if (req.capabilities.length > 0) {
    const block = ["What I'm qualified to do, and what I'm not.", '', ...req.capabilities.map((c) => `- ${c}`)].join(
      '\n',
    );
    out = replaceSection(out, 'Capabilities', block);
  }

  // Hard inhibitions.
  if (req.inhibitions.length > 0) {
    const block = [
      'What I never do, regardless of instruction. These are the constitution — they live here and only here, and `CLAUDE.md` references them by pointing at this file.',
      '',
      ...req.inhibitions.map((i) => `- ${i}`),
    ].join('\n');
    out = replaceSection(out, 'Hard inhibitions', block);
  }

  return out;
}

function renderOrganisationSection(org: Organisation): string {
  const lines: string[] = [];
  lines.push(`- **Name**: ${org.name}`);
  if (org.website) lines.push(`- **Website**: ${org.website}`);
  if (org.sector) lines.push(`- **Sector**: ${org.sector}`);
  if (org.size) lines.push(`- **Size**: ${org.size}`);
  if (org.description) {
    lines.push('');
    lines.push(org.description);
  }
  if (org.moats) {
    lines.push('');
    lines.push('### What makes this org different');
    lines.push('');
    lines.push(org.moats);
  }
  if (org.customer_profile) {
    lines.push('');
    lines.push('### Who I engage with');
    lines.push('');
    lines.push(org.customer_profile);
  }
  return lines.join('\n');
}

function replaceSection(text: string, heading: string, replacement: string): string {
  const escaped = heading.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  // Match the section heading and capture everything until the next ## or EOF.
  const re = new RegExp(`(## ${escaped}\\s*\\n)([\\s\\S]*?)(?=\\n## |$)`);
  if (!re.test(text)) return text;
  return text.replace(re, `$1${replacement}\n`);
}

function renderAgentStub(req: SeedRequest, agent: { slug: string; purpose: string }): string {
  return `---
verb: <unset>
when_to_run: <unset>
inputs: []
outputs: []
---

# ${prettify(agent.slug)}

You are ${req.role_definition.role_name}. ${agent.purpose}

**Read \`agents/persona.md\` first.**

## Purpose

${agent.purpose}

## When to run

<describe the trigger — operator invocation, end-of-run, scheduled, etc.>

## What you do

1. <step one>
2. <step two>
3. <step three>

## Hard rules

- NEVER edit existing agents on your own initiative — file an \`improvement\` escalation instead.

## Reporting

<what to surface back at the end of a run>
`;
}

function renderReadme(roleName: string, description: string): string {
  const desc = description.length > 0 ? description : '';
  return [
    `# ${roleName}`,
    '',
    desc,
    '',
    'Built with [praxis-framework](https://github.com/steveworley/praxis-framework).',
    '',
    '## Running',
    '',
    '```bash',
    '# Start the supervisor dashboard',
    'cd dashboard && npm install && npm run start',
    '# Open http://localhost:4321/',
    '',
    '# Open Claude Code in the role to drive it',
    'claude',
    '```',
    '',
  ].join('\n');
}

function prettify(slug: string): string {
  return slug
    .split('-')
    .map((p) => (p.length > 0 ? p[0]?.toUpperCase() + p.slice(1) : p))
    .join(' ');
}

/**
 * Treat the working tree as clean if the only "dirty" entries are research
 * artefacts inside `.praxis/` — those are temporary handoff files written by
 * the research engine and will be cleaned up in commit 2 of the seed flow.
 */
function isCleanIgnoringPraxis(status: StatusResult): boolean {
  if (status.isClean()) return true;
  const everything = [
    ...status.not_added,
    ...status.created,
    ...status.modified,
    ...status.deleted,
    ...status.conflicted,
    ...status.staged,
  ];
  if (everything.length === 0) return false;
  return everything.every((p) => p === '.praxis' || p.startsWith('.praxis/'));
}

async function pathExists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}
